---
.travis.yml:
  docker_sets:
  - set: centos6-64
  - set: centos7-64
  - set: debian7-64
  - set: debian8-64
  - set: ubuntu1404-64
  - set: ubuntu1604-64
  secure: "iB8hRDwZ1xe+O7IixA34KFBav+oOJZO/UzetZ8u12IJ1e3FJIvBVz49J9XS/xBB9q0j/YiL8WMSzlaejGPUGsR5IOWUer0QuIqKMjJwNR27sn3JO3YHUJ9yprs4mEfOFDCyUqilJ5MCuNYcHlE6G21z5mZKUK0IkpSTqGSt15hpu5YRIEu9ZwUJ66Zy127lH69xVmi6gh1Ntt2X4nAPWtEvkRCD3OLYSooqwgubWaNjaaxJu1xoSpMQjPXZ7sq7dIkzEwAFSjkaTcXRVXdKFEoRG6OpKVTd/Kted9bcYoYJoPKFcXk+43yj1UZPbjk00erSjmPsl2eXE8pVcReZHUbEvu5DO3bSNgoqCeKqsAQX6YuFqlESrk9pSLQeEWSDdIVojhAKUHm8b/QHJDXMpV7e8bFkL2yotzP3+U5y30sMAvyFl44GQv0Hpk4fNemUlD5AQv556Z5b2G0MDWWEog8gSKOun4HHaf9jgsZs7W7RZM6Fal8fUSd1YqvM8p/bPm4bZ+SSfTtGGRAdMu0Dv9VAN0mot4c9q1n93GS/4mPOREnS+9AqJM4SXIXY3m7Es7LscdWdGY9EVriMBfJpCAmPqBGQBzAKgpm5+5vPk0njCyWwdnLhkgA6GJXSB6Bh4hZLkZbrQKlmRLp2qGah045BXAY8PtNkxcJwMFPKN2pE="
